### ISSUE TITLE
Screen does not wake up after update

### ISSUE THREAD

**Issue by ltguillaume** [yuriykulikov/AlarmClock#360]
## Describe the bug

1. Since updating 5 days ago (F-Droid version), alarms do not wake up the phone anymore: the alarm goes off, but the screen remains turned off.

## To Reproduce
Turn screen off and wait for an alarm.

## Expected and observed behavior
Screen turns on, showing the alarm activity, instead of having to turn on the screen manually.

**Comment by yuriykulikov** [comment]
Hello,
which version code is it?

**Comment by ltguillaume** [comment]
v3.08.08, so version code 30808.

**Comment by yuriykulikov** [comment]
Interesting. I have just tested it and it works fine on pixel 4a 5g. Which
device are you using?

**Comment by ltguillaume** [comment]
Samsung S5, LineageOS 17.1 (Android 10). The behavior is fully consistent. I'll check for possibly related logcat entries tomorrow.

**Comment by yuriykulikov** [comment]
I don't know, perhaps try reinstalling the app.
Which was the last version which worked?

**Comment by ltguillaume** [comment]
v3.07.01 worked. I just reinstalled v3.07.01, no issues. Then I uninstalled it and installed v3.08.08 clean, screen stayed off again.

**Comment by ltguillaume** [comment]
<details><summary>Logcat:</summary>
<p>

```
I/ActivityTaskManager(1457):  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30000000 cmp=com.better.alarm/.presenter.AlarmsListActivity} from uid 10138
I/ActivityManager(1457):  Start proc 10494:com.better.alarm/u0a111 for pre-top-activity {com.better.alarm/com.better.alarm.presenter.AlarmsListActivity}
W/OomAdjuster(1457):  Fallback pre-set sched group to default: not expected top priority
D/ConditionProviders.SCP(1457):  onReceive android.app.action.NEXT_ALARM_CLOCK_CHANGED
D/ConditionProviders.SCP(1457):  evaluateSubscriptionLocked cal=ScheduleCalendar[mDays={1, 2, 3, 4, 5, 6, 7}, mSchedule=ScheduleInfo{days=[1, 2, 3, 4, 5, 6, 7], startHour=22, startMinute=0, endHour=7, endMinute=0, exitAtAlarm=true, nextAlarm=Fri Jul 16 16:30:00 GMT+02:00 2021 (1626445800000)}], now=Fri Jul 16 10:50:53 GMT+02:00 2021 (1626425453416), nextUserAlarmTime=Fri Jul 16 16:30:00 GMT+02:00 2021 (1626445800000)
D/ConditionProviders.SCP(1457):  notifyCondition condition://android/schedule?days=1.2.3.4.5.6.7&start=22.0&end=7.0&exitAtAlarm=true STATE_FALSE reason=!meetsSchedule
D/ConditionProviders.SCP(1457):  Scheduling evaluate for Fri Jul 16 22:00:00 GMT+02:00 2021 (1626465600000), in +11h9m6s584ms, now=Fri Jul 16 10:50:53 GMT+02:00 2021 (1626425453416)
E/WindowManager(1457):  App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
D/WindowManager(1457):  powerPress: eventTime=113798476 interactive=true count=1 beganFromNonInteractive=false mShortPressOnPowerBehavior=1
I/PowerManagerService(1457):  Going to sleep due to power_button (uid 1000)...
I/DisplayPowerController(1457):  Blocking screen off
I/DisplayPowerController(1457):  Unblocked screen off after 0 ms
D/ActivityTaskManager(1457):  Top Process State changed to PROCESS_STATE_TOP_SLEEPING
I/DisplayManagerService(1457):  Display device changed state: "Built-in Screen", OFF
I/DreamManagerService(1457):  Entering dreamland.
I/PowerManagerService(1457):  Dozing...
I/DreamController(1457):  Starting dream: name=ComponentInfo{com.android.systemui/com.android.systemui.doze.DozeService}, isTest=false, canDoze=true, userId=0

... Waiting for alarm ...

W/AlarmManager(1457):  Unrecognized alarm listener com.android.server.-$$Lambda$DeviceIdleController$pUAsoxLVwpJ9Ac-b6Wbul1k9bIw@feb7566
D/ImageWallpaper(1930):  onAmbientModeChanged: inAmbient=true, duration=0, mShouldStopTransition=false
D/ImageRevealHelper(1930):  updateAwake: awake=false, duration=0
V/ImageWallpaperRenderer(1930):  onRevealStart: start, anim=false
D/ImageWallpaper(1930):  preRender start
W/Adreno-EGL(1930):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/ImageWallpaperRenderer(1930):  loadBitmap: mBitmap=null
D/ImageWallpaperRenderer(1930):  loadBitmap done, surface size=Rect(0, 0 - 1080, 1920)
D/ImageWallpaper(1930):  preRender end
V/ImageWallpaperRenderer(1930):  onRevealStart: done
V/ImageWallpaperRenderer(1930):  onRevealEnd: start, mScissorMode=false
D/ImageWallpaper(1930):  postRender start
D/ImageWallpaper(1930):  postRender end
V/ImageWallpaperRenderer(1930):  onRevealEnd: done
D/ImageWallpaper(1930):  finishRendering, preserve=true
I/qdhwcomposer(545):  handle_blank_event: dpy:0 panel power state: 0
I/qdhwcomposer(545):  handle_blank_event: dpy:0 panel power state: 0
I/qdhwcomposer(545):  handle_blank_event: dpy:0 panel power state: 0
W/AlarmManager(1930):  Unrecognized alarm listener com.android.systemui.keyguard.-$$Lambda$KeyguardSliceProvider$IhzByd8TsqFuOrSyuGurVskyPLo@82fb3b8
V/SettingsProvider(1457):  Notifying for 0: content://settings/system/next_alarm_formatted
D/ConditionProviders.SCP(1457):  onReceive android.app.action.NEXT_ALARM_CLOCK_CHANGED
D/ConditionProviders.SCP(1457):  evaluateSubscriptionLocked cal=ScheduleCalendar[mDays={1, 2, 3, 4, 5, 6, 7}, mSchedule=ScheduleInfo{days=[1, 2, 3, 4, 5, 6, 7], startHour=22, startMinute=0, endHour=7, endMinute=0, exitAtAlarm=true, nextAlarm=Fri Jul 16 10:52:00 GMT+02:00 2021 (1626425520000)}], now=Fri Jul 16 10:52:01 GMT+02:00 2021 (1626425521527), nextUserAlarmTime=Thu Jan 01 01:00:00 GMT+01:00 1970 (0)
D/ConditionProviders.SCP(1457):  notifyCondition condition://android/schedule?days=1.2.3.4.5.6.7&start=22.0&end=7.0&exitAtAlarm=true STATE_FALSE reason=!meetsSchedule
D/ConditionProviders.SCP(1457):  Scheduling evaluate for Fri Jul 16 22:00:00 GMT+02:00 2021 (1626465600000), in +11h7m58s473ms, now=Fri Jul 16 10:52:01 GMT+02:00 2021 (1626425521527)
D/[      AlarmsReceiver](10494):  Fired 11 NORMAL
D/[         AlarmSetter](10494):  Set 2 (NORMAL) on 16-07-21 16:30:00
D/[              Alarms](10494):  ## Next: Optional(of=Next(isPrealarm=false, alarm=2 [x] 16:30 mtwtfss Windows, nextNonPrealarmTime=1626445800000))
D/[           AlarmCore](10494):  [Alarm 11] Fired -> (NormalSetState > SetState > EnabledState > RootState)
D/[           AlarmCore](10494):  [Alarm 11] NormalSetState.processEvent()
D/[           AlarmCore](10494):  [Alarm 11] NormalSetState -> FiredState
D/[           AlarmCore](10494):  [Alarm 11] exiting [NormalSetState, SetState], entering [FiredState]
D/[           AlarmCore](10494):  11 - com.better.alarm.ALARM_REMOVE_SKIP
D/[     AlarmsScheduler](10494):  skip setting 2 NORMAL on 16-07-21 16:30:00 (already set)
D/[         AlarmSetter](10494):  removeInexactAlarm id: 11
V/SettingsProvider(1457):  Notifying for 0: content://settings/system/next_alarm_formatted
D/ConditionProviders.SCP(1457):  onReceive android.app.action.NEXT_ALARM_CLOCK_CHANGED
D/ConditionProviders.SCP(1457):  evaluateSubscriptionLocked cal=ScheduleCalendar[mDays={1, 2, 3, 4, 5, 6, 7}, mSchedule=ScheduleInfo{days=[1, 2, 3, 4, 5, 6, 7], startHour=22, startMinute=0, endHour=7, endMinute=0, exitAtAlarm=true, nextAlarm=Thu Jan 01 01:00:00 GMT+01:00 1970 (0)}], now=Fri Jul 16 10:52:01 GMT+02:00 2021 (1626425521594), nextUserAlarmTime=Fri Jul 16 16:30:00 GMT+02:00 2021 (1626445800000)
D/ConditionProviders.SCP(1457):  notifyCondition condition://android/schedule?days=1.2.3.4.5.6.7&start=22.0&end=7.0&exitAtAlarm=true STATE_FALSE reason=!meetsSchedule
D/ConditionProviders.SCP(1457):  Scheduling evaluate for Fri Jul 16 22:00:00 GMT+02:00 2021 (1626465600000), in +11h7m58s406ms, now=Fri Jul 16 10:52:01 GMT+02:00 2021 (1626425521594)
W/AlarmManager(1930):  Unrecognized alarm listener com.android.systemui.keyguard.-$$Lambda$KeyguardSliceProvider$IhzByd8TsqFuOrSyuGurVskyPLo@82fb3b8
D/[           AlarmCore](10494):  11 - com.better.alarm.ALARM_ALERT
D/[     WakeLockManager](10494):  Acquired WakeLock{1c8d7d2 held=true, refCount=1} #1
D/[  AlertServicePusher](10494):  pushed intent com.better.alarm.ALARM_ALERT to AlertServiceWrapper
D/[              Alarms](10494):  6 [ ] 11:0 mtwtf__ Meeting
D/[              Alarms](10494):  2 [x] 16:30 mtwtfss Windows
D/[              Alarms](10494):  10 [x] 18:43 mtwtfs_ Alarm name
D/[              Alarms](10494):  11 [x] 10:52 _______ Laundry
D/[         AlarmSetter](10494):  Set 11 (AUTOSILENCE) on 16-07-21 10:57:01
V/SettingsProvider(1457):  Notifying for 0: content://settings/system/next_alarm_formatted
D/ConditionProviders.SCP(1457):  onReceive android.app.action.NEXT_ALARM_CLOCK_CHANGED
D/ConditionProviders.SCP(1457):  evaluateSubscriptionLocked cal=ScheduleCalendar[mDays={1, 2, 3, 4, 5, 6, 7}, mSchedule=ScheduleInfo{days=[1, 2, 3, 4, 5, 6, 7], startHour=22, startMinute=0, endHour=7, endMinute=0, exitAtAlarm=true, nextAlarm=Fri Jul 16 16:30:00 GMT+02:00 2021 (1626445800000)}], now=Fri Jul 16 10:52:01 GMT+02:00 2021 (1626425521703), nextUserAlarmTime=Fri Jul 16 10:57:01 GMT+02:00 2021 (1626425821695)
D/ConditionProviders.SCP(1457):  notifyCondition condition://android/schedule?days=1.2.3.4.5.6.7&start=22.0&end=7.0&exitAtAlarm=true STATE_FALSE reason=!meetsSchedule
D/ConditionProviders.SCP(1457):  Scheduling evaluate for Fri Jul 16 22:00:00 GMT+02:00 2021 (1626465600000), in +11h7m58s297ms, now=Fri Jul 16 10:52:01 GMT+02:00 2021 (1626425521703)
D/[     WakeLockManager](10494):  Acquired service wakelock
D/[        AlertService](10494):  onStartCommand AlarmEvent(id=11, actions=com.better.alarm.ALARM_ALERT)
D/[        AlertService](10494):  activeAlarms: {11=NORMAL}
D/NuPlayerDriver(1274):  NuPlayerDriver(0xa685f0e0) created, clientPid(10494)
I/Codec2Client(1274):  Creating a Codec2 client to service "software"
I/Codec2Client(1274):  Client to Codec2 service "software" created
W/MediaPlayer(10494):  Use of stream types is deprecated for operations other than volume control
W/MediaPlayer(10494):  See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/GenericSource(1274):  FileSource remote
I/GenericSource(1274):  start
D/CCodec  (1274):  allocate(c2.android.vorbis.decoder)
V/C2Store (632):  in init
V/C2Store (632):  loading dll
D/[        AlertService](10494):  [KlaxonPlugin] go (prealarm: false)
D/[        AlertService](10494):  Canceling vibration
D/[        AlertService](10494):  Show notifications: [PluginAlarmData(id=11, alarmtone=Default(persistedString=), label=Laundry)]
D/[        AlertService](10494):  notifications.show(PluginAlarmData(id=11, alarmtone=Default(persistedString=), label=Laundry), 0, true)
D/[        AlertService](10494):  startForeground() for 11
D/[             SERVICE](10494):  startForeground!!! 100000, Notification(channel=com.better.alarm.NotificationsPlugin pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x82 color=0x00000000 category=alarm actions=2 vis=PRIVATE)
D/[     WakeLockManager](10494):  Released WakeLock{1c8d7d2 held=false, refCount=0} #1
I/CCodec  (1274):  Created component [c2.android.vorbis.decoder]
D/CCodecConfig(1274):  read media type: audio/vorbis
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(1274):  extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(1274):  query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig(1274):  c2 config diff is Dict {
D/CCodecConfig(1274):    c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(1274):    c2::u32 input.buffers.max-size.value = 32768
D/CCodecConfig(1274):    c2::u32 input.delay.value = 0
D/CCodecConfig(1274):    string input.media-type.value = "audio/vorbis"
D/CCodecConfig(1274):    string output.media-type.value = "audio/raw"
D/CCodecConfig(1274):    c2::u32 raw.channel-count.value = 1
D/CCodecConfig(1274):    c2::u32 raw.sample-rate.value = 48000
D/CCodecConfig(1274):  }
D/CCodecConfig(1274):  no c2 equivalents for durationUs
D/CCodecConfig(1274):  no c2 equivalents for csd-1
D/CCodecConfig(1274):  no c2 equivalents for channel-mask
D/CCodecConfig(1274):  c2 config diff is   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(1274):    c2::u32 raw.sample-rate.value = 44100
W/Codec2Client(1274):  query -- param skipped: index = 1107298332.
D/CCodec  (1274):  setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (1274):    int32_t channel-count = 2
D/CCodec  (1274):    int32_t max-input-size = 32768
D/CCodec  (1274):    string mime = "audio/vorbis"
D/CCodec  (1274):    int32_t sample-rate = 44100
D/CCodec  (1274):  } and output: AMessage(what = 0x00000000) = {
D/CCodec  (1274):    int32_t channel-count = 2
D/CCodec  (1274):    string mime = "audio/raw"
D/CCodec  (1274):    int32_t sample-rate = 44100
D/CCodec  (1274):    int32_t channel-mask = 3
D/CCodec  (1274):  }
I/MediaCodec(1274):  MediaCodec will operate in async mode
W/Codec2Client(1274):  query -- param skipped: index = 1342179345.
W/Codec2Client(1274):  query -- param skipped: index = 2415921170.
D/CCodecBufferChannel(1274):  [c2.android.vorbis.decoder#626] Created input block pool with allocatorID 16 => poolID 114 - OK (0)
D/BufferPoolAccessor(632):  bufferpool2 0xa5801f58 : 0(0 size) total buffers - 0(0 size) used buffers - 91/97 (recycle/alloc) - 6/96 (fetch/transfer)
D/BufferPoolAccessor(632):  Destruction - bufferpool2 0xa5801f58 cached: 0/0M, 0/0% in use; allocs: 97, 94% recycled; transfers: 96, 94% unfetced
D/BufferPoolAccessor(1274):  bufferpool2 0xa6897a10 : 0(0 size) total buffers - 0(0 size) used buffers - 90/101 (recycle/alloc) - 11/198 (fetch/transfer)
I/CCodecBufferChannel(1274):  [c2.android.vorbis.decoder#626] Created output block pool with allocatorID 16 => poolID 452 - OK
D/CCodecBufferChannel(1274):  [c2.android.vorbis.decoder#626] Configured output block pool ids 452 => OK
D/BufferPoolAccessor(1274):  Destruction - bufferpool2 0xa6897a10 cached: 0/0M, 0/0% in use; allocs: 101, 89% recycled; transfers: 198, 94% unfetced
D/SimpleC2Component(632):  Using output block pool with poolID 452 => got 452 - 0

... Show full-screen alarm ...

I/DreamManagerService(1457):  Gently waking up from dream.
I/DreamManagerService(1457):  Performing gentle wake from dream.
I/ActivityTaskManager(1457):  START u0 {cmp=com.better.alarm/.alert.AlarmAlertFullScreen (has extras)} from uid 10111
W/ActivityTaskManager(1457):  startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x800000 cmp=com.better.alarm/.alert.AlarmAlertFullScreen (has extras) }
D/audio_hw_extn(1273):  audio_extn_get_parameters: returns 
I/hash_map_utils(1273):  key: 'vr_audio_mode_on' value: ''
I/AudioPolicyManagerCustom(1273):  FLAG None hence request for a primary output
W/AudioFlinger(1273):  createTrack_l(): mismatch between requested flags (00000008) and output flags (00000002)
D/AudioFlinger(1273):  Client defaulted notificationFrames to 11466 for frameCount 22932
D/AF::TrackHandle(1273):  OpPlayAudio: track:126 usage:4 not muted
I/PowerManagerService(1457):  Sleeping (uid 1000)...
I/DreamManagerService(1457):  Leaving dreamland.
I/DreamManagerService(1457):  Performing gentle wake from dream.
I/DreamController(1457):  Stopping dream: name=ComponentInfo{com.android.systemui/com.android.systemui.doze.DozeService}, isTest=false, canDoze=true, userId=0
D/audio_hw_primary(1273):  start_output_stream: enter: stream(0xac7d3180)usecase(0: deep-buffer-playback) devices(0x2)
D/audio_hw_primary(1273):  start_output_stream: enter: usecase(0: deep-buffer-playback) devices(0x2)
D/audio_hw_primary(1273):  select_devices: out_snd_device(2: speaker) in_snd_device(0: )
W/msm8974_platform(1273):  Codec backend bitwidth 16, samplerate 48000
D/hardware_info(1273):  hw_info_append_hw_type : device_name = speaker
I/msm8974_platform(1273):  platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
D/ACDB-LOADER(1273):  ACDB -> send_audio_cal, acdb_id = 15, path =  0
D/ACDB-LOADER(1273):  ACDB -> send_adm_topology
D/ACDB-LOADER(1273):  ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(1273):  ACDB -> send_asm_topology
D/ACDB-LOADER(1273):  ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
D/ACDB-LOADER(1273):  ACDB -> send_audtable
D/ACDB-LOADER(1273):  ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER(1273):  ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(1273):  ACDB -> send_audvoltable
D/ACDB-LOADER(1273):  ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
D/ACDB-LOADER(1273):  ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(1273):  ACDB -> send_afe_cal
D/ACDB-LOADER(1273):  ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
D/ACDB-LOADER(1273):  ACDB -> AUDIO_SET_AFE_CAL
D/audio_route(1273):  Apply path: speaker
D/audio_route(1273):  Apply path: deep-buffer-playback
D/audio_hw_primary(1273):  select_devices: done
D/SessionManagerImpl(13705):  unimplemented Method: removeSessionManagerListener
E/WindowManager(1457):  App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
W/View    (1930):  requestLayout() improperly called by com.android.keyguard.CarrierText{83e9d1 V.ED..... ......ID 43,0-762,108 #7f0a01e5 app:id/keyguard_carrier_text} during layout: running second layout pass
D/ImageWallpaper(1930):  onAmbientModeChanged: inAmbient=false, duration=500, mShouldStopTransition=false
D/ImageRevealHelper(1930):  updateAwake: awake=true, duration=500
D/ImageRevealHelper(1930):  transition start
V/ImageWallpaperRenderer(1930):  onRevealStart: start, anim=true
D/ImageWallpaper(1930):  preRender start
W/Adreno-EGL(1930):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/ImageWallpaper(1930):  preRender end
V/ImageWallpaperRenderer(1930):  onRevealStart: done
I/Adreno-EGL(10494):  <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
I/Adreno-EGL(10494):  OpenGL ES Shader Compiler Version: E031.29.00.00
I/Adreno-EGL(10494):  Build Date: 04/04/16 Mon
I/Adreno-EGL(10494):  Local Branch: mybranch19053788
I/Adreno-EGL(10494):  Remote Branch: quic/LA.BF.1.1.3_rb1.12
I/Adreno-EGL(10494):  Local Patches: NONE
I/Adreno-EGL(10494):  Reconstruct Branch: NOTHING
D/StatusBar(1930):  updateQsExpansionEnabled - QS Expand enabled: true
W/Adreno-EGL(10494):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/KeyguardUpdateMonitor(1930):  onKeyguardVisibilityChanged(false)
W/Adreno-EGL(10494):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/StatusBar(1930):  disable<e i a s b H R c s > disable2<q i n >
D/AudioFlinger(1273):  mixer(0xa8a15600) throttle end: throttle time(85)
I/ActivityTaskManager(1457):  Displayed com.better.alarm/.alert.AlarmAlertFullScreen: +333ms
D/StatusBar(1930):  disable<e i a s b h!r!c s > disable2<q i n >
D/ImageRevealHelper(1930):  transition end, cancel=false, reveal=0.0
V/ImageWallpaperRenderer(1930):  onRevealEnd: start, mScissorMode=true
D/ImageWallpaper(1930):  postRender start
D/ImageWallpaper(1930):  postRender end
V/ImageWallpaperRenderer(1930):  onRevealEnd: done
W/Adreno-EGL(1930):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE

W/OpenGLRenderer(1930):  Incorrectly called buildLayer on View: LinearLayout, destroying layer...
W/OpenGLRenderer(1930):  Incorrectly called buildLayer on View: LockIcon, destroying layer...
D/[        AlertService](10494):  Completed fade-in in 1000 milliseconds
D/[        AlertService](10494):  Starting vibration with amplitude -1
D/[        AlertService](10494):  Completed vibration fade-in
D/ImageWallpaper(1930):  finishRendering, preserve=false
I/PowerManagerService(1457):  Waking up from Asleep (uid=1000, reason=WAKE_REASON_POWER_BUTTON, details=android.policy:POWER)...
W/UsageStatsService(1457):  Event reported without a package name, eventType:15

... Manual power press ...

D/WindowManager(1457):  powerPress: eventTime=113826709 interactive=false count=1 beganFromNonInteractive=true mShortPressOnPowerBehavior=1
I/DisplayPowerController(1457):  Blocking screen on until initial contents have been drawn.
D/ActivityTaskManager(1457):  Top Process State changed to PROCESS_STATE_TOP
D/SurfaceFlinger(545):  Setting power mode 2 on display 0
D/qdhwcomposer(545):  hwc_setPowerMode: Setting mode 2 on display: 0
I/DisplayManagerService(1457):  Display device changed state: "Built-in Screen", ON
D/audio_hw_primary(1273):  adev_set_parameters: enter: screen_state=on

W/AlarmManager(1457):  Unrecognized alarm listener com.android.server.job.controllers.idle.-$$Lambda$DeviceIdlenessTracker$-H1-ZwZAJ-vh10A0PeYXaZLj_R0@b255292
W/Adreno-EGL(10494):  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
E/Sensors (531):  Proximity old sensor_state 640, new sensor_state : 512 en : 0
E/Sensors (531):  Acc old sensor_state 512, new sensor_state : 513 en : 1
D/Sensors (531):  ProximitySensor : mHasPendingEvent mEnabled = 0
I/DisplayPowerController(1457):  Unblocked screen on after 218 ms
I/qdhwcomposer(545):  handle_blank_event: dpy:0 panel power state: 1
D/qdhwcomposer(545):  hwc_setPowerMode: Done setting mode 2 on display 0
D/SurfaceFlinger(545):  Finished setting power mode 2 on display 0
W/PowerManagerService(1457):  Screen on took 508 ms
D/[           AlarmCore](10494):  [Alarm 11] Dismiss -> (FiredState > EnabledState > RootState)
D/[           AlarmCore](10494):  [Alarm 11] FiredState.processEvent()
D/[           AlarmCore](10494):  [Alarm 11] EnabledState.processEvent()
D/[           AlarmCore](10494):  [Alarm 11] FiredState -> RescheduleTransition
D/[           AlarmCore](10494):  [Alarm 11] exiting [FiredState, EnabledState], entering [RescheduleTransition]
D/[           AlarmCore](10494):  11 - com.better.alarm.ALARM_DISMISS
D/[     WakeLockManager](10494):  Acquired WakeLock{1c8d7d2 held=true, refCount=1} #2
D/[  AlertServicePusher](10494):  pushed intent com.better.alarm.ALARM_DISMISS to AlertServiceWrapper
D/[              Alarms](10494):  6 [ ] 11:0 mtwtf__ Meeting
D/[              Alarms](10494):  2 [x] 16:30 mtwtfss Windows
D/[              Alarms](10494):  10 [x] 18:43 mtwtfs_ Alarm name
D/[              Alarms](10494):  11 [x] 10:52 _______ Laundry
D/[         AlarmSetter](10494):  Set 2 (NORMAL) on 16-07-21 16:30:00
D/[           AlarmCore](10494):  Repeating is not set, disabling the alarm
V/SettingsProvider(1457):  Notifying for 0: content://settings/system/next_alarm_formatted
W/AlarmManager(1930):  Unrecognized alarm listener com.android.systemui.keyguard.-$$Lambda$KeyguardSliceProvider$IhzByd8TsqFuOrSyuGurVskyPLo@82fb3b8
D/ConditionProviders.SCP(1457):  onReceive android.app.action.NEXT_ALARM_CLOCK_CHANGED
D/ConditionProviders.SCP(1457):  evaluateSubscriptionLocked cal=ScheduleCalendar[mDays={1, 2, 3, 4, 5, 6, 7}, mSchedule=ScheduleInfo{days=[1, 2, 3, 4, 5, 6, 7], startHour=22, startMinute=0, endHour=7, endMinute=0, exitAtAlarm=true, nextAlarm=Fri Jul 16 10:57:01 GMT+02:00 2021 (1626425821695)}], now=Fri Jul 16 10:52:10 GMT+02:00 2021 (1626425530656), nextUserAlarmTime=Fri Jul 16 16:30:00 GMT+02:00 2021 (1626445800000)
D/ConditionProviders.SCP(1457):  notifyCondition condition://android/schedule?days=1.2.3.4.5.6.7&start=22.0&end=7.0&exitAtAlarm=true STATE_FALSE reason=!meetsSchedule
D/[           AlarmCore](10494):  [Alarm 11] RescheduleTransition -> DisabledState
D/[           AlarmCore](10494):  [Alarm 11] exiting [RescheduleTransition], entering [DisabledState]
D/ConditionProviders.SCP(1457):  Scheduling evaluate for Fri Jul 16 22:00:00 GMT+02:00 2021 (1626465600000), in +11h7m49s344ms, now=Fri Jul 16 10:52:10 GMT+02:00 2021 (1626425530656)
D/[              Alarms](10494):  6 [ ] 11:0 mtwtf__ Meeting
D/[              Alarms](10494):  2 [x] 16:30 mtwtfss Windows
D/[              Alarms](10494):  10 [x] 18:43 mtwtfs_ Alarm name
D/[              Alarms](10494):  11 [ ] 10:52 _______ Laundry
D/[        AlertService](10494):  onStartCommand DismissEvent(id=11, actions=com.better.alarm.ALARM_DISMISS)
D/[        AlertService](10494):  no alarms anymore, stopSelf()
D/[        AlertService](10494):  stopping media player
D/NuPlayerDriver(1274):  stop(0xa685f0e0)
V/MediaPlayer(10494):  resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10494):  cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/NuPlayerDriver(1274):  reset(0xa685f0e0) at state 8
D/CCodecBuffers(1274):  [c2.android.vorbis.decoder#626:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
D/CCodecBuffers(1274):  [c2.android.vorbis.decoder#626:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
D/CCodecBuffers(1274):  [c2.android.vorbis.decoder#626:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
D/CCodecBuffers(1274):  [c2.android.vorbis.decoder#626:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 3
D/NuPlayerDriver(1274):  notifyResetComplete(0xa685f0e0)
W/AMessage(1274):  failed to post message as target looper for handler 0 is gone.
D/[             SERVICE](10494):  stopSelf()
D/[     WakeLockManager](10494):  Released WakeLock{1c8d7d2 held=false, refCount=0} #2
D/ActivityTaskManager(1457):  Top Process State changed to PROCESS_STATE_TOP_SLEEPING
V/C2Store (632):  in ~ComponentModule
V/C2Store (632):  unloading dll
W/MediaPlayer(10494):  mediaplayer went away with unhandled events
W/MediaPlayer(10494):  mediaplayer went away with unhandled events
D/[        AlertService](10494):  onDestroy
D/[     WakeLockManager](10494):  Released service wakelock
D/OpenGLRenderer(10494):  endAllActiveAnimators on 0xa11ebc00 (RippleDrawable) with handle 0xa28e9720
```

</p>
</details>

**Comment by WarmChocolateCake** [comment]
Just adding a +1
I'm using a Fairphone 3 running on Android 10.
Downgraded to 3.07.01 and it woke up the screen again. Upgraded to 3.08.08 and the screen remained off again. Only using F-Droid versions.

**Comment by falzonv** [comment]
Hello,

I also observe this bug with 3.08.08 on my Motorola G5 Plus running Android 8.1 (so it is probably not version specific).
Downgrading to 3.07.01, I do not have the bug anymore.

Best regards.

**Comment by yuriykulikov** [comment]
I will try to reproduce this on a Motorola which I have found my drawer. If
if doesn't work out, can anybody help me testing the fix?

**Comment by ltguillaume** [comment]
Sure!

**Comment by yuriykulikov** [comment]
@ltGuillaume @WarmChocolateCake @falzonv I think I got this.

Really appreciate your help! Thank you!

It seems that on some devices with API>=27 calling `setTurnScreenOn(true)` is not enough,
so we will just add all flags regardless of the API level, and call `setTurnScreenOn(true)` if API level is 27+

These two flags were added now:
`WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON`,
`WindowManager.LayoutParams.FLAG_ALLOW_LOCK_WHILE_SCREEN_ON`

Tested on an old Motorola Z3 Play, reproduced the issue and the fix worked as well.

I hope F-Droid will build the update soon.

Best wishes,
Yuriy

**Comment by ltguillaume** [comment]
Thx @yuriykulikov, I will test as soon as it's available through F-Droid! 🙂

**Comment by falzonv** [comment]
Hello @yuriykulikov,

Thank you very much for the quick correction!

---

Just a quick note about F-Droid updates: it will only rebuild the app when there is a new release.

I don't know all the internal details but here is, globally, how this process works:

- Every day, a script "checkupdates" checks all repositories for new releases (using tags, but there may be other ways).
- When a new release is detected, a block of lines about it are appended to the metadata file of the app.
For Simple Alarm Clock, this file is https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.better.alarm.yml
- The build process only works on modified metadata files (that is, on what has been discovered by "checkupdates").

Therefore, the correction you made will only appear in F-Droid after there is a new tag such as 3.08.09 (the total of the discovery, build and publish processes usually takes 4 to 8 days).

*Source: I also have an app on F-Droid :-)*

Best regards.

**Comment by yuriykulikov** [comment]
@falzonv thanks, I have pushed the tag. Now waiting for the F-Droid.

**Comment by ltguillaume** [comment]
I just got v3.08.10 from F-Droid and unfortunately this version still doesn't wake up the screen.

**Comment by yuriykulikov** [comment]
Hey,
fix is available from 3.08.11 and upwards. There seems to be a significant
delay when it comes to publishing new apps.

**Comment by ltguillaume** [comment]
I can now confirm it's working with the latest F-Droid build. Thanks!

I forgot, however, that this bug did "solve" my issue that _every_ alarm I get gets snoozed within seconds if my phone is in my pocket... No pocket dialing, but pocket snoozing, ugh...

**Comment by falzonv** [comment]
Hello @yuriykulikov,

Just tested as well and it works for me too, thank you!

@ltGuillaume: if you are not using the snoozing (but maybe you are in some circumstances?), it can be globally disabled by choosing "Off" for "Repeat after" in the Settings.
This is a setting that I really appreciate compared to the stock clock of my phone where I often accidentally pressed snooze instead of dismiss, causing the alarm to trigger later while I was doing something else.

Best regards.

**Comment by ltguillaume** [comment]
Thanks @falzonv, that will help!

**Comment by yuriykulikov** [comment]
Hm, perhaps I can try to access the proximity sensor to prevent accidental snooze.

**Comment by ltguillaume** [comment]
That would definitely help
